"""added image columnn

Revision ID: 6fc98f44e616
Revises: f8b3812e451c
Create Date: 2024-03-17 16:52:39.749505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc98f44e616'
down_revision = 'f8b3812e451c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
